export const FETCH_SELLERS_REQUEST = "FETCH_SELLERS_REQUEST";
export const FETCH_SELLERS_SUCCESS = "FETCH_SELLERS_SUCCESS";
export const FETCH_SELLERS_FAILURE = "FETCH_SELLERS_FAILURE";

export const ADD_SELLERS_REQUEST = "ADD_SELLERS_REQUEST";
export const ADD_SELLERS_SUCCESS = "ADD_SELLERS_SUCCESS";
export const ADD_SELLERS_FAILURE = "ADD_SELLERS_FAILURE";

