export const LOGIN_REQUEST_ADMIN = "LOGIN_REQUEST_ADMIN";
export const LOGIN_SUCCESS_ADMIN = "LOGIN_SUCCESS_ADMIN";
export const LOGIN_FAILURE_ADMIN = "LOGIN_FAILURE_ADMIN";

export const LOGIN_REQUEST_SELLER = "LOGIN_REQUEST_SELLER";
export const LOGIN_SUCCESS_SELLER = "LOGIN_SUCCESS_SELLER";
export const LOGIN_FAILURE_SELLER = "LOGIN_FAILURE_SELLER";

export const LOGOUT = "LOGOUT";

