export const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";   
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";   
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";   

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";   
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";   
export const ADD_PRODUCT_FAILURE = "ADD_PRODUCT_FAILURE";     

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";   
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";   
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";   
